name: Test
  
on:
  push:
    branches: '**'
  pull_request:
    branches: '**'


jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/devcontainers/typescript-node:20

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install
      run: npm install

    - name: Test
      run: npm run test

    - name: Cover
      run: npm run cover

    - name: Check
      run: npm run check